apiVersion: apps/v1
kind: Deployment
metadata:
  name: wbxzzjsc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wbxzzjsc
  template:
    metadata:
      labels:
        app: wbxzzjsc
    spec:
      containers:
      - image: okteto.dev/wbxzzjsc:latest
        name: wbxzzjsc
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "92de62ec-1041-4d7f-92f7-8c456c3691f8"
        - name: Vless_Path
          value: "/fgh76yjdfgrgjyu"
        - name: Vmess_UUID
          value: "92de62ec-1041-4d7f-92f7-8c456c3691f8"
        - name: Vmess_Path
          value: "/fdbj34gf6ehtd"
        - name: Share_Path
          value: "/v2link"
